name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease > build.log 2>&1 || true

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log

    - name: List output files
      run: ls -R app/build/outputs/apk/release/

    - name: Rename APK
      run: |
        commit_hash=$(git rev-parse --short HEAD)
        apk_file=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
        if [ -f "$apk_file" ]; then
          mv "$apk_file" "app/build/outputs/apk/release/AgentC-release-${commit_hash}.apk"
        else
          echo "No APK file found to rename."
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AgentC-release
        path: app/build/outputs/apk/release/AgentC-release-*.apk
